### ISSUE TITLE
Website broken on narrow screens

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#102]
Content is hidden.

<img width="791" alt="screen shot 2016-06-06 at 21 05 29" src="https://cloud.githubusercontent.com/assets/335567/15845732/baca2b70-2c2a-11e6-9e75-2f0395c3ea6f.png">

There should:
- be test that the navbar is not wider than XXX.
- logo should collapse on small screen. [Svg can be responsive](http://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/)
- be test that the navbar is not wider than XXX.
- be test that the navbar is not wider than XXX.

**Comment by Carreau** [comment]
@ellisonbg when are your summer student working ? Do you have a specific tag for thing you want them to work on ?

**Comment by ellisonbg** [comment]
They start next week full time. Initially I am giving them medium sized
projects that will last about a week on JupyterLab and the website. This
will expand to cover the docs, ipywidgets and notebook as well. They are
initially spending a lot of time just learning as well...

On Mon, Jun 6, 2016 at 9:22 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> when are your summer student
> working ? Do you have a specific tag for thing you want them to work on ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/102#issuecomment-224171474>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0P0N2Scm9Vi5hcfwTGmYTy2ultGOks5qJPIggaJpZM4Ivifo>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment]
What type of sphinx directive? In other words, what would it do?

On Wed, Jun 8, 2016 at 9:52 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Great, feel free to ping me, I think we can do a better job this year if
> we get early good habit.
> We could need to write a custom Sphinx directive for the jupyter doc.
> Would that be a "small" project ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/102#issuecomment-224654899>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0Ahd8X3ryg0oCXiU15d5pTwNKMcRks5qJvNIgaJpZM4Ivifo>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> What type of sphinx directive? In other words, what would it do?

Hum, long to describe... in 2 words:

Take a yaml-like (or whatever) structure and render the content of [this page](http://jupyter.readthedocs.io/en/latest/), which right now is hardcodded as html which prevent cross-linking, force [duplication](https://github.com/jupyter/jupyter/tree/master/docs/source/_templates) of [templates](https://github.com/jupyter/jupyter-sphinx-theme/tree/master/jupyter_sphinx_theme/jupyter) with 1 word change in all of them with jupyter-sphinx-themes, as well as a few other drawbacks.

If yes I can make a longer description.

**Comment by ellisonbg** [comment]
Fernando, Carol, Jamie and I talked yesterday about some docs stuff.
@willingc is going to try to consolidate the build of our docs into a
single repo using git submodules - might solve some of these issues. But
yes, this type of thing might be within scope for the students eventually.

On Wed, Jun 8, 2016 at 10:02 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> What type of sphinx directive? In other words, what would it do?
>
> Hum, long to describe... in 2 words:
>
> Take a yaml-like (or whatever) structure and render the content of this
> page <http://jupyter.readthedocs.io/en/latest/>, which right now is
> hardcodded as html which prevent cross-linking, force duplication
> <https://github.com/jupyter/jupyter/tree/master/docs/source/_templates>
> of templates
> <https://github.com/jupyter/jupyter-sphinx-theme/tree/master/jupyter_sphinx_theme/jupyter>
> with 1 word change in all of them with jupyter-sphinx-themes, as well as a
> few other drawbacks.
>
> If yes I can make a longer description.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/102#issuecomment-224658651>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0GHF-nwkn81mCSUkwsMjnGBbYhVrks5qJvXDgaJpZM4Ivifo>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> Fernando, Carol, Jamie and I talked yesterday about some docs stuff.

is that somewhere ?

> @willingc is going to try to consolidate the build of our docs into a
> single repo using git submodules

I think subtree might be an alternative, and I'm a bit unsure why submodules. 
Travis might be able to consolidate docs in one place though. 


> But
> yes, this type of thing might be within scope for the students eventually.

Do you want me to (try to) make a longer description ?

**Comment by ellisonbg** [comment]
Can you sync up with @willingc to see how her experiment with
subtrees/submobules relates to this?

On Wed, Jun 8, 2016 at 10:52 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> Fernando, Carol, Jamie and I talked yesterday about some docs stuff.
>
> is that somewhere ?
>
> @willingc <https://github.com/willingc> is going to try to consolidate
> the build of our docs into a
> single repo using git submodules
>
> I think subtree might be an alternative, and I'm a bit unsure why
> submodules.
> Travis might be able to consolidate docs in one place though.
>
> But
> yes, this type of thing might be within scope for the students eventually.
>
> Do you want me to (try to) make a longer description ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/102#issuecomment-224673624>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0Hm1f9s81aBcnNrGze2Z_qSkyPLdks5qJwFHgaJpZM4Ivifo>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Sure.

**Comment by willingc** [comment]
@Carreau @ellisonbg I have started tagging some issues in different repos as ``sprint-friendly:calpoly``. Most are docs issues for now but I'm curating issues for a SciPy sprint or the interns to work on as time permits.

**Comment by willingc** [comment]
@Carreau I assigned myself as well here as a reminder to sync up with you on alternative builds of the docs. Doing some research today and tomorrow of some of the large docs projects (sentry, mozilla, openstack, django) to see which use submodules or subtrees. If you have 30 minutes on Friday for a webchat, we can talk about what I find.

**Comment by cameronoelsen** [comment]
@Carreau This doesn't seem to be a problem anymore (I believe I made a fix earlier in the year). Are you still experiencing it? We are also going to be pushing a reworking of the navigation in the next few weeks.

**Comment by Carreau** [comment]
<img width="636" alt="screen shot 2017-08-10 at 10 31 42" src="https://user-images.githubusercontent.com/335567/29183338-24255980-7db7-11e7-8f74-6d07ff0fb08f.png">

No it's better it's still off when exactly at 768px width. You have another funky double transition at 991px -> 992px and 992px -> 993px, but that's in bootstrap.min.css so I doubt you can do anything about these. feel free to close.
