### ISSUE TITLE
"Project" and "Community" sections

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter.github.io#108]
I am not sure what content I should expect in each one of these sections, but oddly, the "Project" section starts with a "Community" subsection...

We could rename "Project" to "Community" or "About" and "Community" to "Resources".

**Comment by willingc** [comment]
@SylvainCorlay Do you think we can close this in light of #103 work?

**Comment by SylvainCorlay** [comment]
Ah, I added a comment in #103 (whch is not merged yet):

> Indeed, as it has been mentioned earlier:

> The Project section is about community, and the page is in fact named About
> The Community page is in fact about finding resources on the project...

> So it is clearly wrong and things should be renamed. I change the Project link to About and Community to Resources rather than connect.

**Comment by willingc** [comment]
@SylvainCorlay Just saw the comment on #103 and left a summary to it. Let's close this one and let #103 keep the conversation all in one place. Simplicity FTW! If you concur, please close this issue ;-)

**Comment by SylvainCorlay** [comment]
:+1:
