### ISSUE TITLE
Issues with SVG images in resources pages

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter.github.io#110]
Some of the SVG images have issues such as intersecting or invisible path (specifically `mail-education.svg`). This is likely to not render ok in every situation. `mail-education.svg` does not render fully on inkscape for example.

Besides, the academic cap icon is a pure US / UK cultural specificity. I think that people would still recognize it everywhere in Europe - but not necessarily as it is embedded like this with other content (the drawer).

**Comment by cameronoelsen** [comment]
Is this still an issue that you face @SylvainCorlay

**Comment by palewire** [comment]
Since this ticket has been inactive for five years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
