### ISSUE TITLE
Haskell notebook on demo page doesn't work

### ISSUE THREAD

**Issue by kojustin** [jupyter/jupyter.github.io#118]
Steps to reproduce
1. Go to https://try.jupyter.org/
2. Click "Welcome to Haskell.ipynb"
3. Click on the first "code cell"
4. Hit SHIFT-ENTER.

I expect the computation to run and the list to print out, instead I see nothing. This happens approximately 100% of the time for me.

I tried with the Python notebook as well and it works around 1/4 times.

**Comment by takluyver** [comment]
Does it remain busy? When I try it, it looks like the kernel never finishes starting. @rgbkrk or @minrk  may be able to get logs.

**Comment by takluyver** [comment]
Does it remain busy? When I try it, it looks like the kernel never finishes starting. @rgbkrk or @minrk  may be able to get logs.

**Comment by kojustin** [comment]
It doesn't seem to remain busy, it just moves focus to the next cell.

**Comment by takluyver** [comment]
What does the `In [ ]:` prompt by the cell you executed look like? Does it have a `*`? Can you provide a screenshot?

**Comment by rgbkrk** [comment]
It takes about 8 seconds for the haskell kernel to start up and be ready. However, I see this behavior as well - the Haskell code appears to never terminate.

**Comment by takluyver** [comment]
Pinging @gibiansky in case this is something he's seen before in other contexts.

**Comment by gibiansky** [comment]
Confirmed, looks like this is a bug in the Haskell kernel. Will look into it and see what I can do to get it working again. (In the meantime it may make sense to remove it, but if possible remove it just temporarily while I get it working again.)

**Comment by gibiansky** [comment]
Or, to clarify, the Docker setup in try.jupyter.org does not have a working Haskell kernel; not sure why (perhaps outdated version of `ihaskell` with newer version of `jupyter`?)

**Comment by rgbkrk** [comment]
[PR welcome](https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile#L100-L108). It looks like ihaskell 0.8.0.0 and ihaskell-widgets 0.2.2.1.

**Comment by cameronoelsen** [comment]
This still seems to be the case, the code cell never seems to complete when I run it either

**Comment by palewire** [comment]
Since this ticket has been inactive for four years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
