### ISSUE TITLE
Add Clemson University to Jupyter users?

### ISSUE THREAD

**Issue by shwina** [jupyter/jupyter.github.io#120]
We at [Clemson University](http://www.clemson.edu/) are proud users of [JupyterHub on our HPC cluster](https://www.palmetto.clemson.edu/jupyterhub/docs/). Could we be listed under the "Currently in use at" section of the home page? Thanks!

**Comment by minrk** [comment]
cc @ellisonbg @cameronoelsen.

@shwina can you provide an institutional logo we should use?

**Comment by shwina** [comment]
Thanks, @minrk; here it is:

![academicsymbolwdm_copur](https://cloud.githubusercontent.com/assets/3190405/18142442/89f5d81a-6f8b-11e6-9caf-5b9270df108e.jpg)

**Comment by go-bears** [comment]
PR #124  resolves this issue #120?

**Comment by go-bears** [comment]
@minrk PR #124 was merged. This issue can be closed now?

**Comment by minrk** [comment]
Yup, thanks @go-bears!
