### ISSUE TITLE
Add Michigan State University to Jupyter users?

### ISSUE THREAD

**Issue by vroomanj** [jupyter/jupyter.github.io#126]
We have just begun using Project Jupyter this semester here at Michigan State University for our new department of Computational Mathematics, Science and Engineering and have had interest expressed from other departments. We would love to have our logo added to jupyter.org if we could be. Attached is a logo to use:

![msu-logo](https://cloud.githubusercontent.com/assets/611430/18549263/7b212ac4-7b1b-11e6-9794-b4dd68640e17.png)

**Comment by go-bears** [comment]
PR #127  resolves this issue?

**Comment by vroomanj** [comment]
The Michigan State logo appears to be much lighter in color than the other logos (does not match). Can this be fixed?

**Comment by rgbkrk** [comment]
It sure can, I'll merge the PR that fixes it.

**Comment by go-bears** [comment]
I pushed a new logo to PR #127 that has darker logo. hope that help!

**Comment by go-bears** [comment]
or should I submit another PR @rgbkrk?

**Comment by rgbkrk** [comment]
We already merged #127, so you'll have to make a new PR.

**Comment by go-bears** [comment]
Got it! Thanks!
