### ISSUE TITLE
Zooming in on mobile causes nav bar to overwhelm viewport

### ISSUE THREAD

**Issue by gnestor** [jupyter/jupyter.github.io#148]
Normal zoom:
![image](https://cloud.githubusercontent.com/assets/512354/19672897/6ffc9088-9a2f-11e6-8cb1-118a8d450f3f.png)

Zoomed in:
![image](https://cloud.githubusercontent.com/assets/512354/19672900/746beb64-9a2f-11e6-9e3b-7f6db2a10f9a.png)

@cameronoelsen One solution is to disable user scaling: Change [this line](https://github.com/jupyter/jupyter.github.io/blob/master/_includes/head.html#L5) to `<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">`. The only issue is that I naturally tried to zoom on my phone because I wanted a closer look at the notebook images, so disabling zooming has its own problems. A hack that I read about is to calculate the amount of scale/zoom in JS and scale the nav bar using `transform: scale(1 - viewportScale)`.

**Comment by Carreau** [comment]
Oh ! Thanks for the precise description.

**Comment by cameronoelsen** [comment]
This seems to have been fixed since this issue opened so I am closing for now!
