### ISSUE TITLE
Design to replace vertical tabs on widgets page

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter.github.io#156]
We are going to have a couple of new examples in the widgets gallery soon

 - the matplotlib widget (jupyter-matplolib)
 - nglview
 - probably the molecular design toolkit.

The current **vertical tabs** are not great from the user experience's perspective.

Besides, for the widgets to benefit from the **resize events**, we should probably use a **phosphor panel** instead of pure css layout.

cc @jasongrout

**Comment by SylvainCorlay** [comment]
@ellisonbg @cameronoelsen 

Since it will become a requirement for us to start using a phosphor widget in place of the current tabs for the widgets gallery, it could be really interesting work on design ideas for such a gallery.

Besides bqplot, pythreejs, ipyleaflet, we will also probably have items with nglview and the autodesk molecular design toolkit, and then ipympl when matplotlib 2.0 is released. I was thinking of a form of carousel with a small image for each library and then a classical document layout for each widget.

**Comment by cameronoelsen** [comment]
@SylvainCorlay Where do we stand with this? I can help out on this page if we wanted to start iterating!

**Comment by palewire** [comment]
Since this ticket has been inactive for four years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
