### ISSUE TITLE
Adding SoundCloud to users via pull request

### ISSUE THREAD

**Issue by nicolabortignon** [jupyter/jupyter.github.io#165]
Hej! 
I'm trying to add SoundCloud to the list of users.
I have a pull request ready in my local branch but no rights to pull it through.

**Comment by takluyver** [comment]
Hi @nicolabortignon . You can use the 'fork' button in the top right to create a copy on Github which you have push access to. Then, from there, you can make a pull request to this repository, which we can merge. Github has an article about it here: https://help.github.com/articles/fork-a-repo/

**Comment by nicolabortignon** [comment]
Perfect,
thanks.
