### ISSUE TITLE
Book section ?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#175]
We had a couple of request to add a list of book about Jupyter. 
For now we can add them to the IPython webside (we have a book section there). 
We should start thinking about what a book section would look like.

**Comment by jhermann** [comment]
Should go to https://github.com/jupyter/jupyter if you ask me.

A new section at either https://jupyter.readthedocs.io/en/latest/reference/content-reference.html or https://jupyter.readthedocs.io/en/latest/content-quickstart.html

**Comment by palewire** [comment]
Since this ticket has been inactive for two years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
