### ISSUE TITLE
GitHub Follow button does not render in footer

### ISSUE THREAD

**Issue by charnpreetsingh** [jupyter/jupyter.github.io#186]
Steps to reproduce:
1. Navigate to jupyter.org
2. Go to About or Resources page
3. Go back to Home page by using the browser's back button
4. Scroll down to footer

Getting the following in my console:
![screen shot 2017-02-06 at 1 53 06 pm](https://cloud.githubusercontent.com/assets/16314651/22667943/b07f0d02-ec73-11e6-81be-6550d8499815.png)

![screen shot 2017-02-06 at 1 53 17 pm](https://cloud.githubusercontent.com/assets/16314651/22667947/b28ec6aa-ec73-11e6-81f1-7804108b402b.png)

**Comment by cameronoelsen** [comment]
Unable to reproduce this in any of the browsers so I am going to close for now.
