### ISSUE TITLE
Widgets page redirects to spam/malware

### ISSUE THREAD

**Issue by ccressent** [jupyter/jupyter.github.io#203]
Visiting https://jupyter.org/widgets.html redirects to some shady spam/malware page.
The problem comes from this script, loaded from unpkg.com:

https://github.com/jupyter/jupyter.github.io/blob/master/widgets.html#L9

Has unpkg.com been hacked?
In any case this is pretty bad and probably needs to be investigated and fixed ASAP...

Related:
https://github.com/unpkg/unpkg.com/issues/31

@SylvainCorlay

**Comment by ccressent** [comment]
The problem was with unpkg and appears to have been fixed:
https://twitter.com/unpkg/status/852669269103869952

**Comment by SylvainCorlay** [comment]
Wow, this is pretty serious. Thanks @ccressent for reporting.
