### ISSUE TITLE
Add a simple redirect to the zero to jupyterhub with kubernetes docs

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/jupyter.github.io#208]
http://zero-to-jupyterhub-with-kubernetes.readthedocs.io/ is kinda large :D 

We should have 'z2jh.jupyter.org' or 'jupyter.org/z2jh' as short URL redirects. I think both @willingc and @minrk are ok with this - just filing this to remember :)

**Comment by willingc** [comment]
I like z2jh.jupyter.org.

**Comment by yuvipanda** [comment]
@minrk can you add a CNAME for this (or give me DNS access? :D)

**Comment by rgbkrk** [comment]
I attempted to share it with you over LastPass sometime ago, you'll need to set up last pass and accept the share @yuvipanda.

![screen shot 2017-05-23 at 3 41 52 pm](https://cloud.githubusercontent.com/assets/836375/26379509/6cedf158-3fce-11e7-9b75-7d83c889f136.png)

**Comment by yuvipanda** [comment]
Thanks @rgbkrk! I've setup z2jh.jupyter.org that performs appropriate redirects!!!

**Comment by rgbkrk** [comment]
Thank you!
