### ISSUE TITLE
Distorted "in use at" logos

### ISSUE THREAD

**Issue by nicktimko** [jupyter/jupyter.github.io#209]
The Clemson and Northwestern University logos are distorted (too tall). They also seem to be the only logos that are scaled inappropriately when the page/browser width is changed.

<img width="1201" alt="screen shot 2017-06-12 at 5 34 45 pm" src="https://user-images.githubusercontent.com/5297556/27058198-7dad4b0c-4f95-11e7-896e-940921fb1aa3.png">

**Comment by minrk** [comment]
Sorry about that. It appears that Firefox handles these things differently, as it so often does. The logos appeared fine on other browsers, which is why I didn't notice. Should be fixed by #220
