### ISSUE TITLE
Anaconda logo is wrong

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#225]
It says "Continuum Analytics".

**Comment by cameronoelsen** [comment]
@Carreau On it!

**Comment by cameronoelsen** [comment]
Fixed in #226

**Comment by slel** [comment]
For context: Continuum Analytics just changed its name to Anaconda.
https://www.anaconda.com/company-blog/continuum-analytics-officially-becomes-anaconda/
