### ISSUE TITLE
Update header, JupyterCon is finished.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#228]
We'll be writing a blog post, we can link to it maybe ?

**Comment by jzf2101** [comment]
@Carreau yes we should make a blog post. Let's make that another issue.

**Comment by teevik** [comment]
Hello is anyone doing this or can i?

**Comment by Carreau** [comment]
> Hello is anyone doing this or can i?

Please; feel free to try and ask if you have any questions.

**Comment by teevik** [comment]
Ok, should the blog post link replace it? Or just remove it?
