### ISSUE TITLE
Add contributor guide link to Community page

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyter.github.io#230]
It seems logical that someone might click Community if they wanted to find their way to either the contributor guide and/or code of conduct. Adding a link to https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html and/or https://jupyter.readthedocs.io/en/latest/community/content-community.html probably in the Community list probably makes sense.

**Comment by thegoobs** [comment]
In the name of Hacktoberfest, I'll take a crack at it. Very new to open source contributing, but I'd like to try this out. It seems simple enough!

**Comment by Carreau** [comment]
Fixed by #230
