### ISSUE TITLE
Information architecture of website

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyter.github.io#231]
I am beginning to work with @jzf2101 to reorganize the Jupyter website. This was work that began with @cameronoelsen doing a tree test on OptimalWorkshop. We have the results of that and are iterating on an outline for the website. Will post our proposed outline here, when ready.

**Comment by ellisonbg** [comment]
This will then be used to drive actual page development.

**Comment by palewire** [comment]
Since this ticket has been inactive for four years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
