### ISSUE TITLE
Add a link to the jupyter github org on the main page?

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter.github.io#24]
There is no direct link to GitHub on the main page of jupyter.org.

We could either have a link to the Jupyter org or to one of the repos. We could use this repo or another one as an entry point with a simple descriptions of the different repositories in the organization.

**Comment by minrk** [comment]
There's a link to the org in the footer of every page.

**Comment by slel** [comment]
@minrk: I don't see that link in the footer. Why not add "CODE REPOSITORY" to the existing "INSTALL / PROJECT / DOCUMENTATION / BLOG / DONATE" headers?

**Comment by willingc** [comment]
@slel If you click on the little octocat with "Follow @Jupyter", you will be linked to the github code repository. If for some reason you do not have this displayed, please let us know.

<img width="1173" alt="screen shot 2015-10-27 at 7 46 03 am" src="https://cloud.githubusercontent.com/assets/2680980/10761503/f3c5ecfe-7c7e-11e5-93cb-6a6d161c7139.png">

**Comment by slel** [comment]
Thanks, I see the button now. The thing is I'm so far no-facebook no-twitter, and I tend to ignore the social-networks follow buttons. By extension I skipped the octocat one. Would it make sense to have "Follow @jupyter on GitHub" and "Follow @ProjectJupyter on Twitter" for these buttons? This way searching for the word "GitHub" using my browser's "find" function would  take me to that button directly.
