### ISSUE TITLE
request about featuring a widget

### ISSUE THREAD

**Issue by cornhundred** [jupyter/jupyter.github.io#271]
Hi, 

Our [group](http://labs.icahn.mssm.edu/maayanlab/) made a Jupyter widget, [Clustergrammer-Widget](https://github.com/MaayanLab/clustergrammer-widget), that can be used to visualize Pandas DataFrames as hierarchically clustered interactive hetamaps (see [example notebook on nbviewer](http://nbviewer.jupyter.org/github/MaayanLab/clustergrammer-widget/blob/master/Running_clustergrammer_widget.ipynb), and [publication](https://www.nature.com/articles/sdata2017151)) . I wanted to know about the possibly getting it featured on the Project Jupyter [widgets page](http://jupyter.org/widgets). Should we submit a pull request, or do widgets need approval, or to meet some criteria? If so we would be interested in finding out more.

Cheers,
Nick

**Comment by palewire** [comment]
Since this ticket has been inactive for three years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
