### ISSUE TITLE
Tracking or Traffic issues  - JupyterCon

### ISSUE THREAD

**Issue by Ruv7** [jupyter/jupyter.github.io#278]
There has been a significant drop (year over year) in traffic from jupyter.org to jupytercon.com. Either something is broken or the placement/size of the JupyterCon message on the home page has affected traffic. Flagging this now and we can discuss further when I have details from the O'Reilly marketing team. #276

**Comment by tgeorgeux** [comment]
@Ruv7 we are currently linking to: 
https://conferences.oreilly.com/jupyter/jup-ny?cmp=ex-data-confreg-home-jpny18_pj_site 
not [jupytercon.com](www.jupytercon.com).
I don't how how O'Reilly is tracking traffic coming in from us. Was there any update after your Tuesday meeting?

**Comment by Ruv7** [comment]
Traffic is down 50% Year over Year (approximately 3,000 clicks instead of 6,000) though it's unclear if that's due to tracking links not being used in the CFP announcement blog post or if it could be placement of the graphic on jupyter.org. As long as we're linking to the proper place there is not much else we can do except move this to a more prominent place asap. We are still investigating if the tracking mechanism is working properly on the back end.

**Comment by Ruv7** [comment]
Closing out this issue. I received word today the tracking link was broken so the large drop in traffic is likely due to this.
