### ISSUE TITLE
Links to mailing list, contact us, help channels

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyter.github.io#28]
Right now there isn't a place on our home page for links to community and development related things. Lots go under these categories:
- Mailing lists
- GitHub repos for governance, enhancement-proposals
- List of all GitHub repos
- Developer guide - how to contribute
- Stackoverflow
- Gitter channels

Before we start to add links in random place, I want to think about the right organization for these resources. This may include working with @captiansafia and others on thinking about the information design and the various personas we are try to address with this information.

**Comment by cameronoelsen** [comment]
@ellisonbg This issue was fixed when we rolled out the community page right?
