### ISSUE TITLE
Facebook, Twitter, Social Media Cards

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/jupyter.github.io#29]
As [reported on Twitter](https://twitter.com/luzfcb/status/638520171875966976) via @luzfcb:

> awesome new site, but still needs some improvement to appear beautiful on facebook share

/cc @cameronoelsen @ellisonbg

**Comment by luzfcb** [comment]
![facebook_](https://cloud.githubusercontent.com/assets/807599/9619334/73583046-50e5-11e5-8ee5-f6f8b599e313.png)

 No image on share. 
This can be solved by creating the [The Open Graph](http://ogp.me/) "meta tags" in head section.

Facebook meta tags: https://developers.facebook.com/docs/sharing/webmasters

Twitter meta tags: https://dev.twitter.com/cards/markup

Linkedin: https://developer.linkedin.com/docs/share-on-linkedin

**Comment by ellisonbg** [comment]
Yep!

On Tue, Sep 1, 2015 at 3:17 PM, Kyle Kelley <notifications@github.com>
wrote:

> As reported on Twitter
> <https://twitter.com/luzfcb/status/638520171875966976> via @luzfcb
> <https://github.com/luzfcb>:
>
> awesome new site, but still needs some improvement to appear beautiful on
> facebook share
>
> /cc @cameronoelsen <https://github.com/cameronoelsen> @ellisonbg
> <https://github.com/ellisonbg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/29>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com
