### ISSUE TITLE
Force https on jupyter.org

### ISSUE THREAD

**Issue by cdvv7788** [jupyter/jupyter.github.io#293]
Currently, the README and other resources point to http://jupyter.org/, and even if the site supports https it does not redirect.

**Comment by westurner** [comment]
HTTPS with HSTS is arguably necessary at least because of the links in the install docs.

- [ ] HSTS
- [ ] Update GH project description link to https://jupyter.org
- [ ] Update README(s)
- [ ] Update link in twitter bio https://twitter.com/ProjectJupyter

**Comment by yuvipanda** [comment]
The 'enforce HTTPS' option on GitHub pages was disabled because the jupyter.org IP was pointed to cloudflare, which then proxies through to github pages (served via fastly). This meant the HTTPS from GitHub pages could not work, since that required the records pointing directly to them (https://help.github.com/articles/troubleshooting-custom-domains/#https-errors).

I have now made the Jupyter IP point directly to the GitHub, and this should let us do https shortly. There should be no downtime either.

**Comment by yuvipanda** [comment]
I've ticked the 'enforce HTTPS' button, and now http redirects to https. GitHub pages does not support HSTS though, so no HSTS for us. If we really want it, we can move back to using cloudflare for HTTPS and proxying - I think they do support HSTS.

**Comment by choldgraf** [comment]
if github forces https then we probably don't need to worry about updating the links manually out in the wild, no? (also #310 made all internal links HTTPS, I think)

**Comment by westurner** [comment]
I'll send gh an email about HSTS.

> if github forces https then we probably don't need to worry about updating the links manually out in the wild, no?

Unfortunately we do because the initial redirect from HTTP to HTTPS can be hijacked.

https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

**Comment by westurner** [comment]
Thanks for getting HTTPS working!

**Comment by yuvipanda** [comment]
I switched HTTPS provisioning back to cloudflare, and turned HSTS on. Thanks for the push, @westurner!

Note that this turned on HTTPS redirection & HSTS for *.jupyter.org (there's no per-domain control in CloudFlare). The only other thing this might impact is nbviewer - I took a quick look and everything seems fine.

**Comment by yuvipanda** [comment]
It looks like I don't actually have rights to edit the description on twitter. @Carreau do you know who might?

**Comment by westurner** [comment]
- [ ] update URL at https://github.com/jupyter-widgets

**Comment by Carreau** [comment]
> It looks like I don't actually have rights to edit the description on twitter. @Carreau do you know who might?

I did, updated to https.

**Comment by lgarron** [comment]
Hello! GitHubber here. This issue just came to my attention.

HSTS is implemented for GitHub Pages. We don't have a UI for it yet, but I can configure domains manually if you'd like to test the feature. I'm happy to add it for `jupyter.org` if someone with sufficient authority specifies in this thread what header you'd like, and understands the implications.

(Note that because there is no UI, you wouldn't be able to *remove* the header without support from me or someone else at GitHub.)

**Comment by Carreau** [comment]
Thanks @lgarron !

@yuvipanda you're likely the one with the most experience there. So far I can see :

```
$ curl -s -D- https://jupyter.org | grep Str
Strict-Transport-Security: max-age=0
```

So we deactivate HSTS headers, and don't apply it to subdomains.
But I'm out of my depth here.

**Comment by lgarron** [comment]
> So we deactivate HSTS headers, and don't apply it to subdomains.

Hmm, in interesting. Perhaps someone did go ahead and configure this in Cloudflare?

**Comment by Carreau** [comment]
> Hmm, interesting. Perhaps someone did go ahead and configure this in Cloudflare?

Looks like it, the settings in cloudflare say this was last changed "a month ago". (annoyed it does not give a more precise date/time).

**Comment by westurner** [comment]
@lgarron I sent a request to support@ asking for HSTS www./apex redirects a
few days ago. AFAIU, there would need to be an additional domain in the
letsencrypt request for one additional www. or Alex domain.

It's probably not necessary to mention that, last I checked, CloudFlare has
to connect to GitHub Pages over HTTP; so it won't work if HSTS is enabled
on both GH Pages and CloudFlare.

CloudFlare does do www./apex redirects with HTTPS and HSTS.

https://github.com/scipy-lectures/scipy-lecture-notes/issues/409#issuecomment-458159627

**Comment by yuvipanda** [comment]
@Carreau @lgarron heya! Thanks for checking back in! I pointed out in https://github.com/jupyter/jupyter.github.io/issues/293#issuecomment-450579855 that I *did* switch back to CloudFlare for HSTS. I think enforcing it for all subdomain is a good thing anyway, so I think I'll keep it there for now...

@lgarron I super appreciate you chiming in here, btw! Do you have a sense if this will be made a user visible option at all?

**Comment by palewire** [comment]
Since this ticket has been inactive for two years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
