### ISSUE TITLE
Add more clear information on how to get involved

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter.github.io#307]
Recently @yuvipanda has been doing some really nice work to improve the developer / contributor documentation for JupyterHub. I worry that the documentation for a package may actually not be a great entry point for certain kinds of potential Jupyter contributors.

How do people feel about the following:

Turn the "community" page into a drop-down list in the nav-bar. The current page will direct to a new page called "email lists" (since it is just a list of email lists). A new page will be added something along the lines of "get_involved.md" that will give information about

1. The kinds of repositories users may want to be involved with.
2. The kinds of contributions Jupyter can use (here it's basically to make it clear that we welcome all kinds of contributions, not just tech contribs)
3. The kinds of tools that Jupyter stuff uses
4. Next steps to repo-specific stuff to get involved.

What do folks think? cc also @jzf2101 since I know she's done a lot of work trying to welcome in new people

**Comment by jzf2101** [comment]
I've been thinking about this as has @tgeorgeux and @willingc ?

**Comment by yuvipanda** [comment]
https://whatcanidoformozilla.org/ is one of my personal favorites.

**Comment by jzf2101** [comment]
I made this https://github.com/jupyter/help/blob/master/CONTRIBUTING.md

**Comment by choldgraf** [comment]
I just discovered that there is already some sort of "contributor guide" documentation here:

https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html

but the only way to get to it (AFAICT) is from the Jupyter "community" page here:

http://jupyter.org/community

**Comment by palewire** [comment]
Since this ticket is more than three years old, I'm going to close it.
