### ISSUE TITLE
Consider using the minimal-mistakes theme for Jekyll

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter.github.io#309]
Right now the Jupyter website is a combination of two different websites - one that's on most of the pages you land on from `jupyter.org`, and another that can be arrived from some of the links *within* pages on jupyter.org (e.g.: https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html).

There's a theme in Jekyll that is well-supported, has nice features, and is *very similar to our current main theme*. It's called [minimal mistakes](https://mmistakes.github.io/minimal-mistakes/).

I don't *think* that migrating our Jekyll template to MM would be a ton of work since we already use Jekyll. Would folks be +1 on me giving a shot at making this migration? It could potentially allow us to standardize the design of the website using a tool that we all know is relatively well battle-tested.

(note that there have also been conversations around changing the website build setup entirely, see #234 ...I don't want this issue to suggest I think that's a bad idea, but I'm hoping this could be a relatively quick win with our current setup)

**Comment by tgeorgeux** [comment]
I know we've been thinking about moving Gatsby in the medium/long term. How much work do you think it would be to migrate the entire website, and what would the main benefits of this theme be over what we have now?

**Comment by rgbkrk** [comment]
As a rough measure, I tend not to contribute to jekyll based sites (unless it's just a content change) and will contribute to gatsby based ones. I love that I can use React components within Gatsby.

**Comment by choldgraf** [comment]
@rgbkrk that is a good reason to use one over the other :-)

Do you find gatsby sites to be more maintainable, better community, etc?

**Comment by palewire** [comment]
Since this ticket has been inactive for three years old, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
