### ISSUE TITLE
Logo in docs

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#31]
I discover yesterday that you can put a logo in the sidebar of readthdocs. Example:  https://flit.readthedocs.org

Do you think that would be useful for  jupyter related docs to have a visual Jupyter logo ?

@ellisonbg @cameronoelsen ?

**Comment by rgbkrk** [comment]
Yes please!

**Comment by go-bears** [comment]
Has this been assigned yet?

**Comment by Carreau** [comment]
> Has this been assigned yet?

No you can try to do it.

**Comment by cameronoelsen** [comment]
We have since made a Jupyter-specific sphinx theme (https://github.com/jupyter/jupyter-alabaster-theme) that fixes this issue!
