### ISSUE TITLE
"Learn more" JS widgets are not centered on jupyter.org

### ISSUE THREAD

**Issue by ericdill** [jupyter/jupyter.github.io#324]
There are three "Learn more' widgets at the bottom of jupyter.org. The text inside of them is not centered inside of the animated widget:
<img width="851" alt="off-center-2" src="https://user-images.githubusercontent.com/6223243/53884941-9bc84000-3fea-11e9-9e01-970d1b6db0a4.PNG">
<img width="853" alt="off-center" src="https://user-images.githubusercontent.com/6223243/53884942-9bc84000-3fea-11e9-88e2-e569631f966c.PNG">

If I knew how to fix this, I'd submit a PR. Alas I know almost nothing about JS / CSS.

I am on windows 10 version 1803 and Firefox 64.0.2.

**Comment by choldgraf** [comment]
hey @ericdill , thanks for spotting this! I believe that we're going to discuss the state of the website, and improvements that can be made, at a community meeting next week! We should discuss this issue there as well!

**Comment by jasongrout** [comment]
It looks like this is solved now. I checked on Chrome, Firefox, and Safari on macOS.
<img width="1313" alt="Screen Shot 2021-07-16 at 8 48 49 AM" src="https://user-images.githubusercontent.com/192614/125974771-a9f8e09e-dbe8-4852-8799-d66be5988a56.png">

Closing as resolved, but please comment/reopen if you are still seeing this. Thanks!
