### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by cameronoelsen** [jupyter/jupyter.github.io#33]
After speaking with Brian and hearing that we should highlight our community of contributors along with the steering council that leads the project, I have added two sections to the about page and also tweaked the design to be more consistent. The community section spiderweb is going to utilize d3js and show how everyone has contributed and helped one another. Hope you like the mockup! (All of the supporting text is filler that I made up, so don't worry about that :) )
![concept](https://cloud.githubusercontent.com/assets/6437976/9672453/d575822c-524f-11e5-912a-b4f40dd9f9d4.png)

**Comment by Carreau** [comment]
Did you meant to close ?

**Comment by Carreau** [comment]
-1 on d3 graph, all website that use a dynamic graph make my CPU usage rise too high. 
Well you can still try, but if on tests it does that I'll will be -1.
