### ISSUE TITLE
JupyterLab 1.0 Announcement.

### ISSUE THREAD

**Issue by tgeorgeux** [jupyter/jupyter.github.io#338]
This issue is to track the JupyterLab 1.0 announcement on the main Jupyter.org page.

We are shooting to have a section on the front page similar to the notebook and JupyterHub sections to coincide with the 1.0 announcement. I've been working on the copy [on a Jupyterlab issue](https://github.com/jupyterlab/jupyterlab/issues/6789) and would love some feedback on [the copy for the announcement](https://docs.google.com/document/d/121TIhinWKpPGNr9TZZlsicSvGpfNEjJjgwP0orvwjiM/edit).

**Comment by choldgraf** [comment]
this is out now, yeah?

**Comment by tgeorgeux** [comment]
Closed via #340
