### ISSUE TITLE
CSS bug in the documentation page

### ISSUE THREAD

**Issue by woswos** [jupyter/jupyter.github.io#361]
Hi,
I realized the small bug in the [documentation page](https://jupyter.org/documentation) while browsing the website:

<img width="1680" alt="Screen Shot 2020-05-04 at 4 54 19 PM" src="https://user-images.githubusercontent.com/10498874/81231342-01ce9f80-8fc1-11ea-8fe0-ce960ee27a9d.png">

**Here are some options I tried**

Making the cards taller:
<img width="756" alt="Screen Shot 2020-05-06 at 6 04 26 PM" src="https://user-images.githubusercontent.com/10498874/81233213-427be800-8fc4-11ea-8ff7-9613fa90a12e.png">

Decreasing the font size:
<img width="961" alt="Screen Shot 2020-05-06 at 6 05 34 PM" src="https://user-images.githubusercontent.com/10498874/81233229-47d93280-8fc4-11ea-913f-6a9cee3c61d0.png">

Replacing "Community maintained kernels" with a shorter text:
<img width="951" alt="Screen Shot 2020-05-06 at 6 04 56 PM" src="https://user-images.githubusercontent.com/10498874/81233221-4576d880-8fc4-11ea-9ef9-985bf905b427.png">

What do you think about these?

**Comment by tgeorgeux** [comment]
Thanks for noticing this! I think adding some logic that scales the entire row up to make space for the largest box is the easiest path forward.

**Comment by woswos** [comment]
This idea is even better! Let me try to implement it.
