### ISSUE TITLE
jupyterlab demo out of date (version 1.0.10)

### ISSUE THREAD

**Issue by ianhi** [jupyter/jupyter.github.io#376]
The link for jupyterlab on try.jupyter.org is: https://github.com/jupyter/jupyter.github.io/blob/459acf4446fc58f58d556cdac833d28b823e1125/_data/try.yml#L13 which leads to an outdated version:
![image](https://user-images.githubusercontent.com/10111092/88121738-add16100-cb94-11ea-97ef-32aaf5d136eb.png)

It looks like this link is tied to tag on that repo that has not been updated: https://github.com/jupyterlab/jupyterlab-demo/tree/try.jupyter.org

This URL could be switched to https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab  or that git tag could be updated.

**Comment by choldgraf** [comment]
hmmm - that's a good point. Ping @jasongrout or @ellisonbg - what would you like to do here?
