### ISSUE TITLE
404 for Contributing Guide

### ISSUE THREAD

**Issue by sgibson91** [jupyter/jupyter.github.io#377]
Hi all,

I noticed the link to the contributing guide on the [community page](https://jupyter.org/community) is broken. Since many Jupyter projects (at least the ones I work on) reference this in their own contributing guidelines, I think it would be great if we could figure out where this page has moved to?

Cheers!

**Comment by slel** [comment]
The page formerly at

https://jupyter.readthedocs.io/en/latest/contributor/content-contributor.html

is now at

https://jupyter.readthedocs.io/en/latest/contributing/content-contributor.html

**Comment by slel** [comment]
Pull request:

https://github.com/jupyter/jupyter.github.io/pull/378

**Comment by choldgraf** [comment]
Thanks so much @slel for noticing and making the patch!

**Comment by slel** [comment]
Credit goes to @sgibson91 who noticed the faulty link and opened this ticket!
