### ISSUE TITLE
Asset/Content build chain

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/jupyter.github.io#38]
#7 should sleep until we have a story about how to build the site from more collaboration-friendly sources than raw CSS, JS, and HTML.
## Features

Here's some things that we should be able to do:
- install bower assets
- build optimized
  - css (less?)
  - js
  - images
- build pages
  - markdown
  - notebooks
    - whatever we end up choosing with should support (or we should build) a plugin to 
- reusable site components (menus, etc).
- static site search?
- sitemaps/SEO
- content syndication (releases from GH, blogs, books, cons, etc).
- dead link checking
## Workflow

I am imagining we would want to something set up where PRs come in against a `build` branch, and Travis would push to `master`? 
## Platforms

There are [many, many options](https://www.staticgen.com/) (hey, anything we like there for #7?). Yeoman is a lovely place to look for [bootstrapping this process](http://yeoman.io/generators/) with most modern tools, but we might end up with some more bespoke stuff :)
- `make` + whatever 
- ruby
  - [Jekyll](https://jekyllrb.com/)
    - would "just work" with gh-pages, but we'd end up needing node stuff and python stuff (to get [notebooks](http://cscorley.github.io/2014/02/21/blogging-with-ipython-and-jekyll/))
- node
  - [metalsmith](http://www.metalsmith.io/)
- python
  - [pelican](http://blog.getpelican.com/)
    - probably still need node, but this at least has a [notebook plugin](https://github.com/danielfrg/pelican-ipynb)
- sphinx
  - really not very pro this for a "designed" site, but if we're going to continue using it primarily for docs, it may make sense to keep the common build chain

**Comment by palewire** [comment]
Since this ticket has been inactive for six years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
