### ISSUE TITLE
Add better discovery of all Jupyter orgs and repos

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter.github.io#397]
As we've grown, we've added a number of new orgs and repos to Project Jupyter. It's difficult to keep track of all of the activity across all the repos and orgs.

Once https://github.com/jupyter/governance/pull/94 lands, it would be great to incorporate the list into this website.

**Comment by choldgraf** [comment]
100% this would be great - it is very difficult for those who are not "in the know" to navigate the Jupyter landscape and understand the different projects, organizations, people, etc.
