### ISSUE TITLE
pydata.org/project/project-jupyter/ page renders incorrectly

### ISSUE THREAD

**Issue by jakelevirne** [jupyter/jupyter.github.io#401]
I looked, but couldn't find a pydata.org repo for their site source. But I thought folks here might care to know that https://pydata.org/project/project-jupyter/ appears to have rendering issues. Screenshot attached.
<img width="1384" alt="Screen Shot 2021-02-17 at 9 18 56 AM" src="https://user-images.githubusercontent.com/51732/108217212-55018100-7101-11eb-98fc-275007d06bc8.png">

**Comment by choldgraf** [comment]
maybe @aterrel could advise?

**Comment by aterrel** [comment]
This is a Wordpress issue. I’ll bug the folks at web@pydata.org in the morning. Martey or Walker will need to look into it.

**Comment by aterrel** [comment]
FYI, I haven't heard back from the NumFOCUS staff that manages the word press. I believe some folks have been displaced by the weather. Will keep following up.

**Comment by choldgraf** [comment]
Thanks @aterrel no worries

**Comment by martey** [comment]
This should be fixed now.

**Comment by Carreau** [comment]
FIxed indeed, thanks.
