### ISSUE TITLE
What is the rationale for the elements included in the navbar

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#433]
Currently, here is the order of links in the nav:
- Install
- About Us
- Community
- Events
- Documentation
- NBViewer
- JupyterHub
- Widgets
- Blog
- Security

It's unclear to me why these particular elements were chosen. One step to tighten and improve the Jupyter site would be to clarify the reasoning behind what's in the nav and then to edit what appears there to match.

From my outside point of view, it's seems a little strange to include NBViewer and JupyterHub at that level of the hierarchy. They are just two subprojects among many. If they are there, why not also Voila or JupyterLab or anything else?

Also, while I find the widgets page useful, there does not appear to be much of any discussion of widgets on the homepage, which makes we wonder why they would merit such high placement on the nav.

I'm interested to hear what others think, but my initial proposal would be to trim this list to subpages that are strictly "meta" information about Project Jupyter itself at the highest level, leaving out subprojects.

**Comment by Carreau** [comment]
In response to this and your previous #432

I think the rational has changed a lot during the years, and as you might have seen, there is not much people taking care of the website. 

The list was much smaller at the beginning and it was easy to add everything. 

There has been a few attempt to redo the website, and my personal opinion is the following on the many attempts:
 - Every attempt was attempting to redesign the whole site without any consideration of who was going to implement the new design and who would write the content. This mistake was done at least twice.

The current attitude is more I believe a default of accepting anything as long as it's not definitely wrong, and helps. The exact scope of Jupyter is a bit fuzzy, so what goes or not is hard.

**Comment by palewire** [comment]
Thanks for the read out on this. My take is that the fundamentals of the site are good.

Rather that mess around with the backend technology, or launching a frontend revolution, I think that a few rounds of light edits and optimizations can help the current site shine. Thanks for putting up with all my PRs. I'll likely continue nibbling around the edges until I drive everyone crazy. ;)

Looking again at the top nav items, they do appear to fall into one of two buckets.

**Metadata about Project Jupyter**

- About Us
- Community
- Events
- Documentation
- Blog
- Security

- Jupyter products and projects

- NBViewer
- JupyterHub
- Widgets

The only one that is a little bit of both is `Install`.

My outsider's take would be that the products listed in the nav now feel a bit cherry picked. Why does JupyterHub have a navitem, but not a homepage section? And why don't the products on the homepage stack, like JuptyerLab, appear in the nav?

One edit I could image would be remove those products from the nav, which would trim down what's there, and provide a clearer scope to what's included.

**Comment by Carreau** [comment]
> Thanks for putting up with all my PRs. I'll likely continue nibbling around the edges until I drive everyone crazy. ;)

I think I am the one that should thank you for sending them. 

I believe that "install" is a special case as it is one of the highest question we got.

I'm happy to remove items from the nav bar, but indeed the question is why some and not others. Different stakeholder have different visions, and it is sometime relatively hard to reconcile.



> or launching a frontend revolution

What you disagree with #234 and #347 ?  :-)

**Comment by krassowski** [comment]
I can see a case for having a special place for NBViewer and Binder. While `Install` capture JupyterLab/Notebook/Widgets, most users will not install NBViewer or Binder: they will use it. Maybe we should have a drop down item for things like that?

Further, I think that we should not cut stuff out based on our hunch alone: is there any analytics data that we could use to make an informed decision (do visitors use that link this to access nbviewer? would anyone be upset about it leaving without having an alternative link elsewhere first? If no one uses it, that could be an argument in favour of moving it to a less prominent place).

**Comment by palewire** [comment]
What analytics data is there available?

**Comment by krassowski** [comment]
Huh, it seems there is none currently (since May): https://github.com/jupyter/jupyter.github.io/pull/408. I wonder if someone has archival data that could be exported for the purpose of this discussion?

**Comment by palewire** [comment]
This has now been superseded by other tickets and pull requests.
