### ISSUE TITLE
Lighthouse reports Bootstrap and jQuery dependencies have vulnerabilities

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#439]
It might be worth looking at refactoring the JS on the page to see if we can write a small amount of homebrewed stuff and remove these dependencies entirely.

![Screenshot from 2021-11-20 04-25-40](https://user-images.githubusercontent.com/9993/142726239-c8085281-23b1-4a6f-a122-c1583a22c1f9.png)

**Comment by krassowski** [comment]
Can bump versions to use newer patch releases in the meantime?

**Comment by palewire** [comment]
I tried that and I think the patch releases still have the issues.

**Comment by Carreau** [comment]
I don't think those security warnings are critical as we are a purely static website. 
And those will be complicated to remove as they are due to use embedding widgets.

I understand it is annoying for ranking, but other that that it has no effects.
