### ISSUE TITLE
SageMath logo issue.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#44]
There seem to be an rendering issue with sagemath logo. 

It seem that some text have been traced, and not all, which might lead to rendering issue if font not present on target computer. 

We should re-trace the logo.

**Comment by minrk** [comment]
cc @ellisonbg @cameronoelsen for website/logo stuff

**Comment by haraldschilly** [comment]
Attached is an svg that should have the same background grey tone like you are using and the font has been rendered as a path. I assume that's better, although I don't know exactly what has been done, or needs to be done, to make it fit for the website.

edit: github doesn't allow svg attachments, hence it's [here](https://cloud.sagemath.com/92848d19-8432-46c8-ba59-2b0d9521c9f2/raw/marketing/logo/smc-logo-jupyter.svg)

**Comment by willingc** [comment]
@cameronoelsen Here's a new svg from @haraldschilly. Thanks @haraldschilly :sunflower:

**Comment by slel** [comment]
Fixed by https://github.com/jupyter/jupyter.github.io/pull/48
This issue (which is really about SageMathCloud logo rather than SageMath) can be closed. Thanks!
