### ISSUE TITLE
Let's settle the serial comma question once and for all

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#453]
The site is inconsistent. Sometimes there is a serial comma at the end of lists. Like here:

![Screenshot from 2021-12-03 07-15-59](https://user-images.githubusercontent.com/9993/144626772-01f10e0a-67db-4f12-9a10-635bdd784eae.png)
![Screenshot from 2021-12-03 07-16-13](https://user-images.githubusercontent.com/9993/144626816-d3d6e5f4-95c1-459c-81c2-cdc3af920fde.png)

Sometimes there isn't one. Like here:
![Screenshot from 2021-12-03 07-16-43](https://user-images.githubusercontent.com/9993/144626879-62153141-501f-47ce-9e96-ff822063ac77.png)
![Screenshot from 2021-12-03 07-16-27](https://user-images.githubusercontent.com/9993/144626884-3ae1793c-25d7-4bf6-8914-0b6e662eb147.png)

Whether or not to include that final comma is, obviously, a subjective question of style. I am not invested in one side or the other. As someone who spends his days as a pedantic editor by trade, I seek only consistency.

That said, forced to choose, I would vote against the extra comma. When it comes to type, less is almost always more. The stylebooks of the Associated Press and The New York Times agree.

Let's pick one or the other. Then I'll be happy to submit a PR that smooths out inconsistencies.

**Comment by ivanov** [comment]
@palewire thanks for catching the inconsistency (not to mention all the other work you've been putting in!). I prefer to keep the  serial comma in.

**Comment by palewire** [comment]
Since the serial comma has been the style up until now, with nobody all that fired up either way about this ticket I'm going to defer to _stare decisis_ and patch all lists to use that form.
