### ISSUE TITLE
The NASA logo could be better

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#488]
Kinda small and has a weird background right now.
![Screenshot from 2021-12-11 12-57-03](https://user-images.githubusercontent.com/9993/145691379-34dc231b-333a-4b05-9ef3-550df83e44ed.png)

**Comment by LancelotHayward** [comment]
While looking at the SVG I also noticed it had some red and blue in it on the inside of the letters. I didn't touch those.
I'm new to GitHub so I hope I did stuff right
