### ISSUE TITLE
Big blank space among documentation cardlist

### ISSUE THREAD

**Issue by krassowski** [jupyter/jupyter.github.io#490]
Why is there a big blank space on https://jupyter.org/documentation?

![Screenshot from 2021-12-11 21-02-42](https://user-images.githubusercontent.com/5832902/145691573-13acf574-3e1d-4a81-8f8c-3bf931214a33.png)

@palewire do you remember if it was like that before?

Well this is why adding before/after screenshots is useful.

**Comment by palewire** [comment]
@krassowski, this must be a bug in my effort to replace the jQuery plugin with a pure CSS solution. Apologies. I can debug.

**Comment by krassowski** [comment]
It is not clear to me if it was indeed your refactor, or if it was broken earlier too. Maybe we should re-write it to use CSS grid?

**Comment by palewire** [comment]
@krassowski There's a patch in #491. I would support a grid rewrite. My PR will better standardize the HTML between the two uses of the boxes. I think your proposal would be a good follow up after the bug is squashed.

**Comment by palewire** [comment]
@krassowski Tho, my quick second thought is that I would love to see #473 merged before taking further CSS refactoring. It's going to make life easier for everyone writing the code to get SCSS into the mix.
