### ISSUE TITLE
Active tab highlighting is not consistent in the navigation bar

### ISSUE THREAD

**Issue by krassowski** [jupyter/jupyter.github.io#500]
It seems that recent refactoring might have broken highlighting of the active page in the navigation tab:

![active-page-not-highighted](https://user-images.githubusercontent.com/5832902/146674737-18839592-ff37-497a-a121-32847115f1be.gif)

It works well for About us, Documentation, and Widgets but not for the other tabs in the nav bar.

**Comment by palewire** [comment]
Could we fix this by using the URL, not the page title, in the loop test [here](https://github.com/jupyter/jupyter.github.io/blob/master/_includes/header.html#L36-L38)

**Comment by krassowski** [comment]
Yes, this looks like a good idea. Or maybe we could test both (with **or** operator)?

**Comment by krassowski** [comment]
It looks like it is happening again?

**Comment by palewire** [comment]
I probably screwed it up when I refactored the nav. Will look.
