### ISSUE TITLE
Homepage descriptions should do a better job differentiating Jupyter Lab from Jupyter Notebook

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#509]
Lab:
>JupyterLab is a web-based interactive development environment for notebooks, code, and data. Its flexible interface allows users to configure and arrange workflows in data science, scientific computing, computational journalism, and machine learning. A modular design allows for extensions that expand and enrich functionality.

Notebook:
> The Jupyter Notebook is a web application for creating and sharing documents that contain code, visualizations, and text. It can be used for data science, statistical modeling, machine learning, and much more.

Both mention data science and machine learning. There really isn't anything that separates the two. What are the key distinctions to strike?

**Comment by krassowski** [comment]
I believe that Notebook is well defined by the text in https://github.com/jupyter/enhancement-proposals/pull/79:

> **The Notebook as a document-centric user experience:** The Jupyter Notebook application offers a _document-centric user experience_. That is, in the Notebook application, the landing page that contains a file manager, running tools tab, and a few optional extras, is a launching point into opening standalone, individual documents. This document-centric experience is important for many users, and that is the first key point this proposal aims to preserve. Notebook v7 will be based on a different JavaScript implementation than v6, but _it will preserve the document-centric experience, where each individual notebook opens in a separate browser tab and the visible tools and menus are focused on the open document_.

Starting with v7 (assuming that JEP 79 passes) both will be modular and extensible with the same toolset; the interface of Lab will not change: it will be the more extensible, configurable and flexible UI allowing workflows which require multiple panes with notebooks, files and visualisations to be open simultaneously. In a way [Elyra](https://github.com/elyra-ai/elyra) (and many similar distributions) demonstrate that JupyterLab is also a **platform** for developing a domain-specific applications.

I personally think of JupyterLab as the notebook-driven data science and analysis IDE where the workflow is focused on working with notebooks (which differentiates it from generic IDEs) and of Notebook as a "Google Docs" for the world of Notebooks - fast simple, good for users who need to focus on a single document (i.e. for teaching/tutorials).
