### ISSUE TITLE
Sponsor logos are not flowing properly

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#517]
The rows and columns are jumbled. This should probably be rewritten with a flexbox layout.
![Screenshot from 2021-12-22 04-43-32](https://user-images.githubusercontent.com/9993/147094721-f5a5c515-f713-4ee1-af0b-93db68df45e2.png)

**Comment by sunnyjain15699** [comment]
Time to flex my flexbox skills. Can you do the honours @palewire  ?

**Comment by palewire** [comment]
@sunnyjain15699, sadly I think this one already got fixed and merged.
