### ISSUE TITLE
About page cards should run two columns on mobile

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#519]
The current flow is single column at mobile sizes and it leaves too much whitespace on the right. A two column layout would be better.

![Screenshot from 2021-12-22 05-16-58](https://user-images.githubusercontent.com/9993/147098727-fac9daa4-7d5e-4e41-9ff5-e8ec79ab4d34.png)

**Comment by sunnyjain15699** [comment]
Hi @palewire . Can you define the mobile size. I mean the resolution, upto 405px X 672px , you see about images in two columns. But from less than 405px X 672px. It displays single image. In iphone X you will see single column, do you want to have double column in that too ?
