### ISSUE TITLE
Some buttons have no :hove style

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#52]
Mainly on main page, the "Learn more" dont' react while other button do.

**Comment by Carreau** [comment]
Donate via pay-pal have no hover either. (To fix once jekyll work is done)

**Comment by go-bears** [comment]
I can try to to help with this. did you want the change made to bootstrap.css or materialize.css?

**Comment by Carreau** [comment]
likely [logo-nav](https://github.com/jupyter/jupyter.github.io/blob/master/css/logo-nav.css) bootstrap and materialize should be as-is from upstream in case we update them.
