### ISSUE TITLE
Text alignment of names in About page cards is screwy

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#520]
Sometimes the name is right aligned, sometimes center aligned, sometimes right align. This should be standardized.
![Screenshot from 2021-12-22 05-18-38](https://user-images.githubusercontent.com/9993/147098859-097e16ca-64ba-48be-9a0b-d6ca1d43ed00.png)
![Screenshot from 2021-12-22 05-18-31](https://user-images.githubusercontent.com/9993/147098860-20471028-ee40-41f3-b797-5b426b5056d6.png)

**Comment by slel** [comment]
These all seem left aligned with quite some margin.

**Comment by krittiyaclark** [comment]
I want to help with this issue. Can you assign the ticket to me please?

**Comment by palewire** [comment]
It's all yours, Krittiya! The site now supports SCSS so feel free to run wild with that.

**Comment by sunnyjain15699** [comment]
Hi @palewire . I changed the alignment as it is required. Below is the screenshot. Let me know if anything else needs to be done or if you have any comments.

Is it fine? 

![changing  about image people](https://user-images.githubusercontent.com/44168572/147676674-b6d95932-ff11-4ac6-b5c9-c8aaf616966a.png)

**Comment by krittiyaclark** [comment]
> 

Thank you! I forked the repo and tried to run it locally but looks like it needs Ruby. What else do I need to install to be able to run it?

**Comment by palewire** [comment]
You can find instructions here https://github.com/jupyter/jupyter.github.io#jupyters-main-website
