### ISSUE TITLE
Audit HTML structure with W3C validator

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#526]
I suspect the page is in pretty good shape, but running our HTML through https://validator.w3.org/ would be a good way identify any minor bugs in our layout.

**Comment by sunnyjain15699** [comment]
Hi! Would like to help you out in this issue. Show me the light.

**Comment by palewire** [comment]
You've been assigned the ticket. I think a good first step would be to go the w3c validator linked above and run the jupyter homepage through it. You could either start the patch whatever bugs you find there yourself, or post screenshots of the results here to log what's needed.

**Comment by sunnyjain15699** [comment]
I have a query which is , I need to check those pages that are build in the _site folder that got created after the build has been processed.

**Comment by sunnyjain15699** [comment]
This is the link where you can see the result, also I have the setup in my local as well @palewire  : https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fjupyter.org%2F

**Comment by sunnyjain15699** [comment]
You  can check the PDF from here as well, it includes :
[W3Validator including images, source .pdf](https://github.com/jupyter/jupyter.github.io/files/7789182/W3Validator.including.images.source.pdf)

**Comment by palewire** [comment]
@sunnyjain15699, that's great! Thank you. There are some simple, clear things to fix in there if you want to try to take any of them on.

**Comment by sunnyjain15699** [comment]
Would love to take all of them. Are you going to create more issues officially from the one we identified w3c validator ? @palewire

**Comment by palewire** [comment]
I hadn't thought it thru. If you want to make the tickets, or just start putting in pull requests, I'd be fine with that. Let me know how I can help.

**Comment by krassowski** [comment]
I think the ultimate goal should be to have a GitHub Action which verifies HTML integrity continuously. I don't know of such action, but IMO we should keep it open until we have a task on CI ensuring that we do not get regressions.

**Comment by sunnyjain15699** [comment]
> I think the ultimate goal should be to have a GitHub Action which verifies HTML integrity continuously. I don't know of such action, but IMO we should keep it open until we have a task on CI ensuring that we do not get regressions.

So, basically you want to automate the task of W3C validator. Or may be when we redeploy the application , it should validate the HTML structure in real time ?

**Comment by sunnyjain15699** [comment]
> I hadn't thought it thru. If you want to make the tickets, or just start putting in pull requests, I'd be fine with that. Let me know how I can help.

I will start making the changes and make the pull requests correspondingly.

**Comment by krassowski** [comment]
> So, basically you want to automate the task of W3C validator.

Yes

> Or may be when we redeploy the application , it should validate the HTML structure in real time ?

Maybe.

https://github.com/marketplace/actions/html5-validator is an example of an action we could use.

**Comment by sunnyjain15699** [comment]
> > So, basically you want to automate the task of W3C validator.
> 
> Yes
> 
> > Or may be when we redeploy the application , it should validate the HTML structure in real time ?
> 
> Maybe.
> 
> https://github.com/marketplace/actions/html5-validator is an example of an action we could use.

How can I help in the automation part with html5-validator ? Can you shed some light or point to a direction ?

**Comment by krassowski** [comment]
I will take care of automation.
