### ISSUE TITLE
fix url scheme.

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#53]
Once jekyll stuff is done, convert url `foo.html`  to `/foo/` for cleaner abstraction and better referencing.

**Comment by go-bears** [comment]
I'm new to to juypter project, but I'd like to help. This sounds like a newbie task that I'd like to take this on. which files need changing?

**Comment by Carreau** [comment]
just rename things like

about.html -> about/index.html
donate.html -> donate/index.html

should be sufficient, after we look through the various files to make sure the links are correct. 

And potentially drop files with redirects (but not sure how exactly)

**Comment by Carreau** [comment]
[this](https://help.github.com/articles/redirects-on-github-pages/) might be of help.

**Comment by palewire** [comment]
Since this ticket has been inactive for six years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
