### ISSUE TITLE
Utilize native lazy-loading to reduce initial page load

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#532]
As [described by Google](https://web.dev/browser-level-image-lazy-loading/), native lazy loading is now support in Chrome and Firefox. It is an easy tool to increase speed on pages with lots of images.

The homepage and the about page each bring in dozens of logos and images below the initial viewport. These images are ideal candidates for lazy loading. Let's implement the feature.

**Comment by dn-flixee** [comment]
I would really like to work on this issue. Can you guide me through it ?

**Comment by palewire** [comment]
@dn-flixee, sure thing. Take a look at two things:

1) The [official Google docs](https://web.dev/browser-level-image-lazy-loading/) on the issue
2) My [proposed implementation for the homepage](https://github.com/jupyter/jupyter.github.io/pull/533). 

Then see if you can figure out how to do the same thing for the /about page, which has many many images below the initial viewport.

**Comment by dn-flixee** [comment]
Hello @palewire , is your implementation for homepage, is not merged into master ?

**Comment by dn-flixee** [comment]
Hello @palewire . I have made the changes, where do I have to push it, on which branch ?

**Comment by palewire** [comment]
My changes are not in master yet. I'd recommend making your own branch and sending a pull request separate from that.

Have you made a pull request before?

**Comment by dn-flixee** [comment]
Okay. I just asked one of my friends. I forked the repo, then pushed the local code by creating a new branch (developLazyLoading) on the forked repo. Now I want to perform pull request. Which branch should I target ?

**Comment by palewire** [comment]
Go ahead and target the master branch

**Comment by dn-flixee** [comment]
oh Okay. Done! Thank you so much.

**Comment by palewire** [comment]
This is done.
