### ISSUE TITLE
Tagline on interior pages is too narrow on mobile

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#537]
Let's add some CSS to fix this

![Screenshot_20211226-044405](https://user-images.githubusercontent.com/9993/147404525-e4e98e7d-e5f4-418b-9d36-8fda4d3b5d5e.png)
![Screenshot_20211226-044351](https://user-images.githubusercontent.com/9993/147404529-eed90c3f-c01e-43e3-a08b-65cec1ef3c5a.png)

**Comment by FantasqueX** [comment]
I think adding one line of CSS `    line-height: 1.5;` can solve this problem. Here is a comparison of the effect before and after the change captured on my Edge simulated as iPhone X:
Before:
![image](https://user-images.githubusercontent.com/46747123/147405624-610541e6-36a7-4861-a59c-7cf66c115476.png)
After:
![image](https://user-images.githubusercontent.com/46747123/147405641-89dea035-58c6-41aa-9bd5-4485eae49bfd.png)

Just add to this [place](https://github.com/jupyter/jupyter.github.io/blob/3b3b0884e2134c8356cc42f2ab4d2d809242b098/_sass/_nav.scss#L175).

For the picture below, maybe we need to add a new class in which changing the line height.

If you agree with me, I'll create a pull request to fix things.

**Comment by palewire** [comment]
I agree the vertical line height could use some work. A patch would be welcome.

However, with this ticket I was trying to describe the horizontal width of the elements, which I think should be wider. 

![Screenshot_20211226-062838](https://user-images.githubusercontent.com/9993/147406664-6f54feda-6510-4d87-8fc7-2d5f680c534a.png)

**Comment by FantasqueX** [comment]
I see that. After some investigation, I found it was due to 
```
.header p {
  margin: 0 30%;
}
```
in https://github.com/jupyter/jupyter.github.io/blob/23b60f4f5b621a7c76687aa27cf371b067e22c36/_sass/_nav.scss#L216.
It was designed for PC only and wasn't designed for mobile devices. 
I think changing the CSS rule to below can help.
```
.header p {
    width: calc(max(240px, 40%));
    margin: 0 auto;
}
```
Before:
![image](https://user-images.githubusercontent.com/46747123/147408772-0f9f37f5-8f7a-4efe-93be-16680cb6f4e4.png)

After:
![image](https://user-images.githubusercontent.com/46747123/147408761-37cf7bdf-e672-4a1b-b410-205ed7adde17.png)

The specific value is still debatable, this value is surely casual.

**Comment by palewire** [comment]
Thanks for finding it. Do we need the calc and percentage? Could a simple `max-width` do it?

**Comment by FantasqueX** [comment]
I don't think it is enough. Because of `margin: 0 30%;` , the subtitle gets a 30% margin. If just add `min-width: 240px`,  it no longer centered, as following.
![image](https://user-images.githubusercontent.com/46747123/147411724-555f795e-79e9-4a38-9040-ee44f66fa31c.png)
I'm not an expert of CSS, and don't know why :(

**Comment by palewire** [comment]
Ah. Try something more like:

```
max-width: 240px 
margin-left: auto;
margin-right: auto;
```

**Comment by FantasqueX** [comment]
The problem is
```
.header p {
    margin: 0 30%;
}
```
defines 30% left and right margin for PC. If your suggestions above are used, then the margin becomes `auto` for PC. I don't want to break the old behavior, so I use `calc()`.

**Comment by palewire** [comment]
Does the margin auto not work at desktop sized viewports? I had assumed it would.

**Comment by FantasqueX** [comment]
`auto` margin worked at desktop sized viewports. However, what I care about is the previous devloper thinks it should be 30% margin rather than auto margin. If you think they are similar, then `auto` margin is OK.

**Comment by FantasqueX** [comment]
I have made many suggestions in this issue, but the contributions do not include me. What should I do to avoid this situation? Ask for an assignment before?

**Comment by FantasqueX** [comment]
https://github.com/jupyter/jupyter.github.io/pull/568/commits/bd02e46fff473d6cc34dbe7a98d15d8c8b7fa5d3
In this commit, I found the code I suggested `line-height: 1.5` , I think only me have the right to contribute this line of code.

**Comment by palewire** [comment]
@FantasqueX, making a pull request is the way to submit your code. GitHub has some good documentation on how to make them happen if you haven't done it before. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

**Comment by choldgraf** [comment]
@FantasqueX thanks for your suggestions here - the way that workflows for Jupyter (and in GitHub in general) work is:

- Issues are places for discussion and ideas, they are a place to come to agreement about what should be done, and give a path forward for somebody to implement when they have the time
- Pull Requests are the way that we propose a specific change to the codebase. You can open a pull request via [the docs @palewire linked to](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) after making the change on your local copy of the repository, in a dedicated branch.
- Git encodes authorship as "the person that made a code commit in the pull request".
- Pull Requests generally link back to the issues that they close, which is another place to recognize the people that participated in conversation around how an issue was resolved

In general, git-based workflows, and GitHub in general, do not have a good way to provide attribution to the people that participated in conversation around the code - they over-emphasize the people that added the code themselves. This is an unfortunate reality of these platforms, but nonetheless we appreciate ideas and discussion like you comments above, so thanks!

**Comment by FantasqueX** [comment]
> @FantasqueX thanks for your suggestions here - the way that workflows for Jupyter (and in GitHub in general) work is:
> 
> * Issues are places for discussion and ideas, they are a place to come to agreement about what should be done, and give a path forward for somebody to implement when they have the time
> * Pull Requests are the way that we propose a specific change to the codebase. You can open a pull request via [the docs @palewire linked to](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) after making the change on your local copy of the repository, in a dedicated branch.
> * Git encodes authorship as "the person that made a code commit in the pull request".
> * Pull Requests generally link back to the issues that they close, which is another place to recognize the people that participated in conversation around how an issue was resolved
> 
> In general, git-based workflows, and GitHub in general, do not have a good way to provide attribution to the people that participated in conversation around the code - they over-emphasize the people that added the code themselves. This is an unfortunate reality of these platforms, but nonetheless we appreciate ideas and discussion like you comments above, so thanks!

@choldgraf Thanks for suggestions! Next time I will make a pull request myself.

**Comment by FantasqueX** [comment]
> @FantasqueX, making a pull request is the way to submit your code. GitHub has some good documentation on how to make them happen if you haven't done it before. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests

@palewire What I want to say is I don't think you have the right to contribute code suggested by others.

**Comment by choldgraf** [comment]
@FantasqueX apologies if it came across as aggressive for someone else to implement the code suggestion. I do not believe @palewire was attempting to take credit - it is a very common practice for one person to suggest code in an issue, and for another person to implement it in a pull request. We do not have any community practices that prevent one person from implementing ideas that another person has suggested. It is helpful and encouraged for people to suggest code in issues, so that the person who makes a pull request has guidance

**Comment by FantasqueX** [comment]
Got it, maybe I'm too agressive. Now I understand.

**Comment by choldgraf** [comment]
No worries @FantasqueX and thanks so much for sharing ideas and guidance with others 🙂
