### ISSUE TITLE
Container padding on mobile is wider than it needs to be

### ISSUE THREAD

**Issue by palewire** [jupyter/jupyter.github.io#541]
I think we can safely reduce the padding in the left and right gutters on mobile. That could give the content a little more space to shine. Nothing big needed, just a little trim.
![Screenshot_20211226-072751](https://user-images.githubusercontent.com/9993/147408025-669650ca-946c-4561-b726-0c3caa26c795.png)

**Comment by dn-flixee** [comment]
@palewire Is this good? I have changed the padding from 30px to 15px.
![Screenshot from 2021-12-27 23-08-31](https://user-images.githubusercontent.com/52662739/147494971-7b2cb4d0-77da-4883-8c0a-b550b4a8bfe0.png)

**Comment by palewire** [comment]
Yes. That's a good fix for sure.
