### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by krassowski** [jupyter/jupyter.github.io#580]
https://github.com/jupyter/jupyter.github.io/pull/579 highlighted some broken links. I fixed a few, but others require some more research making it a good first issue. These are

- About:
   - [ ] https://douglasblank.com/ (CC @dsblank)
   - [x] http://sundellopensource.se
   - [ ] http://yuvi.in (CC @yuvipanda)
   - [x] https://www.sloan.org/
   - [x] https://techblog.netflix.com → this seems to be https://netflixtechblog.com/ now?

- Index:
   - [x] https://codeneuro.org
   - [x] https://www.nyu.edu
   - [x] https://www.quantopian.com

- Binder:
   - [x] https://binderhub.readthedocs.io/en/latest/federation/federation.html

Part two:
- [x] hub.html: `assets/hublogo.svg`
- [x] index.html: `https://nyu.edu`
- [x] widgets.html: `https://k3d-jupyter.readthedocs.io/en/latest/showcase/index.html`

**Comment by krassowski** [comment]
Hi @yuvipanda and @dsblank, this is a gentle nudge on your URLs.
- @yuvipanda I think that `https://words.yuvi.in/` is the correct one, is this fine to change it to that one?
- @dsblank it looks like `http://douglasblank.com/` does exist but it does not have any content (and importantly `https`); should we use that one, none, or another website?

**Comment by krassowski** [comment]
Adding:
- hub.html: `assets/hublogo.svg`
- index.html: `https://nyu.edu`
- widgets.html: `https://k3d-jupyter.readthedocs.io/en/latest/showcase/index.html`

**Comment by yuvipanda** [comment]
@krassowski thank you for digging this up! And yes, words.yuvi.in is the right one!

**Comment by krassowski** [comment]
Thanks! Closing as fixed in #627
