### ISSUE TITLE
Hard to read on large screens

### ISSUE THREAD

**Issue by krassowski** [jupyter/jupyter.github.io#591]
Some pages are very wide making it difficult to read on large screens:

![Screenshot from 2021-12-31 23-35-48](https://user-images.githubusercontent.com/5832902/147841098-ffed16fe-db53-4b55-a15c-1f1bcdf0640f.png)

the pictures feel detached from the content on the right. Back on #516 it felt a bit better:

![Screenshot from 2021-12-31 23-42-25](https://user-images.githubusercontent.com/5832902/147841168-7cce4f26-e648-4a65-ac86-838806a59ad5.png)

But I think we should just add a max-width or something to the base layout. What do others think?

**Comment by palewire** [comment]
What size are you using here?

**Comment by krassowski** [comment]
This is standard 4K UHD resolution.

**Comment by palewire** [comment]
Copy. Once my current round of PRs get handled I'd like to refactor the homepage structure. There are a lot of crusty divs and css classes that need to get tidied. This bug could get fixed in that push.
