### ISSUE TITLE
fix "Donate" link in footer

### ISSUE THREAD

**Issue by slel** [jupyter/jupyter.github.io#60]
The "Donate" link in the footer of the home page points to about.html instead of donate.html.

**Comment by willingc** [comment]
@slel Thanks for the report :sunny:

@cameronoelsen The footer menu items "Donate" and "Project" link to the home page instead of the correct sub-page.

**Comment by cameronoelsen** [comment]
I'll fix that when we get back in the office

**Comment by Carreau** [comment]
Thanks, fixed !

**Comment by willingc** [comment]
Thanks! Fixed by #64
