### ISSUE TITLE
add gitter sidecar on website?

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#65]
I know i one those who don't like gitter,  still integrating sidecar seem like a good idea:

https://sidecar.gitter.im

Thought ?

**Comment by ellisonbg** [comment]
Yeah, I saw that, but I think we want fewer users showing up on gitter, not
more. ?

On Thu, Oct 29, 2015 at 2:16 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> I know i one those who don't like gitter, still integrating sidecar seem
> like a good idea:
>
> https://sidecar.gitter.im
>
> Thought ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/65>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
Agreed, I just wanted to point out that solution exist. 

I, personally am slightly negative. 
Though if there is a gitter button I don't see a reason not to have it trigger sidecar.

**Comment by ellisonbg** [comment]
I am -1 to a gitter button on the homepage I think

On Thu, Oct 29, 2015 at 2:29 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Agreed, I just wanted to point out that solution exist.
>
> I, personally am slightly negative.
> Though if there is a gitter button I don't see a reason not to have it
> trigger sidecar.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/65#issuecomment-152276568>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by willingc** [comment]
Is there a Contact us? section on the homepage or site? I ask because where would we want the users to go with general questions. I assume to the Google Group for Jupyter. The upside of the Jupyter google group is that questions have been respectfully and thoughtfully answered.

**Comment by ellisonbg** [comment]
Given our moving away from chat for users, I am going to close this.
