### ISSUE TITLE
Our Donate section has broken CSS

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter.github.io#656]
Our Donate page: https://jupyter.org/about

has some sub-optimal CSS that seems unintentional. Note that it seems to be expecting a button-like setup, but there is no button and the spacing is off:

![chrome_l0IcaRg6Y0](https://user-images.githubusercontent.com/1839645/149580480-e6504f1e-7335-4bc4-be07-cc94295cfb1d.png)
t

@palewire think this is related to some of the recent bootstrap changes?

(also a meta-note, that "donation" section is not very discoverable, I'd be +1 on putting a big "donate" link on the landing page or top-bar)

**Comment by palewire** [comment]
I think this will be fixed by #653
