### ISSUE TITLE
Update "Try" page to use JupyterLab 4

### ISSUE THREAD

**Issue by JasonWeill** [jupyter/jupyter.github.io#727]
The ["Try" page](https://jupyter.org/try) links to JupyterLite demos, based on JupyterLab 3. We should offer a way to try JupyterLab 4 in browser, preferably not using Binder at this time, to save on our Binder capacity.

**Comment by ivanov** [comment]
Thanks for this report, @JasonWeill, not sure when this happened, but it currently uses `@jupyterlab/application v4.0.7` so going to go ahead and close this one.
Happy hacking! :bowtie:
