### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by jtpio** [jupyter/jupyter.github.io#752]
Currently manually typing and entering `jupyter.org` in the browser address bar might sometimes redirect to http://jupyter.org instead of https://jupyter.org :

[jupyter-org-https.webm](https://github.com/jupyter/jupyter.github.io/assets/591645/91384e9e-d762-4b2b-9eec-509afba88af1)

It would be nice to enforce HTTPS by default.

Normally this can be done via the repo settings. I don't have access to the settings of this repo, but this is what it looks like with another repo:

![image](https://github.com/jupyter/jupyter.github.io/assets/591645/5e0598cd-d442-489e-b4d9-45b53d8b2cd3)

**Comment by jtpio** [comment]
Of note some browsers like Firefox might upgrade to HTTPS automatically:

![image](https://github.com/jupyter/jupyter.github.io/assets/591645/f437f90f-4696-48de-bfc3-cedee9144431)

**Comment by ivanov** [comment]
thanks @jtpio , done!
![image](https://github.com/jupyter/jupyter.github.io/assets/118211/50e0ee75-3d8a-4931-907c-0b963143a002)
