### ISSUE TITLE
Hamburger by default

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyter.github.io#78]
On a 13" laptop, the hamburger shows by default, making it very difficult to navigate the site. We need to reconsider the design of the page header. Krug talks about this in "Don't Make Me Think" - basically that _everything_ wants to be on the front-page above the fold, making it more or less useless. Not everything can be equally important...

**Comment by ellisonbg** [comment]
@cameronoelsen

**Comment by cameronoelsen** [comment]
@ellisonbg The only reason why we had to do this was because of the new community link at the top of the page, the bar items would collide with the logo on the left. An alternative to having the community landing page on the top bar would be to add it to the community section on the about page. We could also make it so that as the bar scales down in resolution, we could change the font size and width between the tab bar items.

**Comment by Carreau** [comment]
Like GitHub Does, we can collapse the Jupyter logo to only the planet and moon on smaller screen.

The Donate link does not need to be a separate page either IMHO.

**Comment by ellisonbg** [comment]
I want to clarify - I don't think the solution in this case is one of
visual design. We simply have too much content trying to be important in
the header. Fixing that will require us having less content in the header
that is trying to be important. Options:

* Just removing stuff.
* Using nesting in our website layout rather than a flat heirarchy. Then
the site nag bar would have dropdown menus in some cases.

Cheers,

Brian



On Wed, Feb 17, 2016 at 2:43 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Like GitHub Does, we can collapse the Jupyter logo to only the planet and
> moon on smaller screen.
>
> The Donate link does not need to be a separate page either IMHO.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/78#issuecomment-185442763>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
For the time being, I think we should take down the community page from the website until I can take a pass at the page's design (if we need an entire page for it) and figure out where it should be nested in the navigation. Currently, I think that the card design it is using is kind of confusing for this particular situation.

Ana and I were thinking that the page should give the user all of the different means of communications (like it currently is) but displayed different and give the user some context on what mean of communication is used for what. If you visited it right now blindly as someone who has never gotten in contact with the Jupyter community, it is very confusing on where to post questions, suggestions and what each website does for us specifically.

This would also fix the navigation bar issue we are having with the hamburger icon for the time being while we restructure the navigation bar.

**Comment by cameronoelsen** [comment]
We have replaced the hamburger menu on desktop with a full navigation showing with all of the items. Since this is fixed and we will be compacting the current navigation in the coming weeks, I am going to close this issue
