### ISSUE TITLE
Update website with new NumFOCUS information

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyter.github.io#83]
Got this from NumFOCUS:

"We'd really like to make sure that our relationship to sponsored projects is clearly delineated on each project's individual website. To that end, we're requesting all sponsored projects to take the following steps: Please post the NumFOCUS digital stamp on the homepage of your website (at the bottom or in the footer is fine). Link the image to this url: www.numfocus.org"

@cameronoelsen can you work with Ana to tackle this?

**Comment by cameronoelsen** [comment]
@ellisonbg Yeah no problem! Ill try to get this pushed as soon as possible.

**Comment by Ruv7** [comment]
@ellisonbg - we do have the following at the bottom of our Project Page, do you think they're aware of this and the request is specifically that we put the logo on the home page or do you think that may be clear enough? 

![image](https://cloud.githubusercontent.com/assets/16657753/14474916/297a290a-00b4-11e6-9428-83adedff03bb.png)

**Comment by ellisonbg** [comment]
Their request was made to all NumFOCUS projects generically. It is up to us
though to interpret that is a way that best serves our website. I think it
is important for us to show we are affiliated with NumFOCUS and the bottom
of that page may not be sufficient. But that doesn't mean we need to put
their logo at the top of the home page.

On Tue, Apr 12, 2016 at 1:43 PM, Ana Ruvalcaba <notifications@github.com>
wrote:

> @ellisonbg <https://github.com/ellisonbg> - we do have the following at
> the bottom of our Project Page, do you think they're aware of this and the
> request is specifically that we put the logo on the home page or do you
> think that may be clear enough?
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/16657753/14474916/297a290a-00b4-11e6-9428-83adedff03bb.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/83#issuecomment-209094623>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Ruv7** [comment]
Got it, I'm working with Cameron to come up with a feasible option. We should have a suggestion tomorrow or Friday at the latest.

**Comment by palewire** [comment]
Since this ticket has been inactive for five years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
