### ISSUE TITLE
Investigate using a dropdown in the nav bar

### ISSUE THREAD

**Issue by Carreau** [jupyter/jupyter.github.io#87]
Note to self:
investigate how to make dropdown menu with jekyll.

**Comment by ellisonbg** [comment]
I am going to have Team 1 at Cal Poly start to work on this.

**Comment by palewire** [comment]
Since this ticket has been inactive for five years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.

**Comment by krassowski** [comment]
Actually, this is the same as https://github.com/jupyter/jupyter.github.io/pull/497#issuecomment-997383958 so let's keep this one open - I think it would be very useful to manage items which are desired in navbar.

**Comment by palewire** [comment]
Cool. To my underdeveloped mind, at this moment, I think the root issue here is what to do with pages that have been left out of the current nav like /conduct, /binder and /hub.

**Comment by palewire** [comment]
I think we resolved this ticket with the discussion in #529.
