### ISSUE TITLE
how to create an embed-jupyter-widgets

### ISSUE THREAD

**Issue by zkk995** [jupyter/jupyter.github.io#88]
Is there any examples of how to use an embed-jupyter-widgets? I think it is an amazing feature.

**Comment by takluyver** [comment]
Ping @jdfreder

**Comment by takluyver** [comment]
And @SylvainCorlay , for good measure

**Comment by palewire** [comment]
Since this ticket has been inactive for five years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
