### ISSUE TITLE
Working on widget showcase page

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter.github.io#92]
I got some prototype working for a widget showcase page very similar to http://www.htmlwidgets.org/showcase_leaflet.html
presenting what can be done with widgets in static web pages. 

I am trying to make this work with the jupyter.org css styling and all but I am having trouble building it locally. Are there other steps missing that are not documented on how to build the jupyter.org website?

cc @cameronoelsen @Carreau

**Comment by ellisonbg** [comment]
What did you need to do to get it to build?

On Sat, May 28, 2016 at 11:15 AM, Sylvain Corlay <notifications@github.com>
wrote:

> Closed #92 <https://github.com/jupyter/jupyter.github.io/issues/92>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/92#event-675257145>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0GlKME1pyB5rjN1QM-y9kPZhGBObks5qGIY2gaJpZM4Io3CY>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
This is more of a gem + osx issue so not really related to this repo.

**Comment by ellisonbg** [comment]
I am asking because I have students who will need to build this on OSX by
intalling gems, etc.

On Sat, May 28, 2016 at 11:25 AM, Sylvain Corlay <notifications@github.com>
wrote:

> This is more of a gem + osx issue so not really related to this repo.
>
> On Sat, May 28, 2016 at 2:23 PM, Brian E. Granger <
> notifications@github.com>
> wrote:
>
> > What did you need to do to get it to build?
> >
> > On Sat, May 28, 2016 at 11:15 AM, Sylvain Corlay <
> notifications@github.com
> > >
> > wrote:
> >
> > > Closed #92 <https://github.com/jupyter/jupyter.github.io/issues/92>.
> > >
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/jupyter/jupyter.github.io/issues/92#event-675257145
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AABr0GlKME1pyB5rjN1QM-y9kPZhGBObks5qGIY2gaJpZM4Io3CY
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Brian E. Granger
> > Associate Professor of Physics and Data Science
> > Cal Poly State University, San Luis Obispo
> > @ellisonbg on Twitter and GitHub
> > bgranger@calpoly.edu and ellisonbg@gmail.com
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/jupyter/jupyter.github.io/issues/92#issuecomment-222322504
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ACSXFv2EVZkc0ev9S1FYhf5IF_7YRHpGks5qGIgYgaJpZM4Io3CY
> >
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/92#issuecomment-222322612>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0CiA1mJzOHQvJQnqglsq0aA3kW5xks5qGIidgaJpZM4Io3CY>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
There is a lot of things to do for the jupyter.org website. @cameronoelsen wants submenu in dropdown, and there is a **gigantic necessary refactor** to do of the documentation template. I unfortunately do not have the bandwidth to also take care of that.

**Comment by ellisonbg** [comment]
I am going to have a student team tackle the dropdowns in the nav bar as a
first project. That team has 2 devs+2 designers.

On Sat, May 28, 2016 at 12:11 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> There is a lot of things to do for the jupyter.org website. @cameronoelsen
> <https://github.com/cameronoelsen> wants submenu in dropdown, and there
> is a *gigantic necessary refactor* to do of the documentation template. I
> unfortunately do not have the bandwidth to also take care of that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/92#issuecomment-222324900>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0O4JfYt3BR6jr0RdH1DwaGIM4uRNks5qGJN2gaJpZM4Io3CY>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by SylvainCorlay** [comment]
Well I dropped my mac and got back to my ubuntu lenovo...

**Comment by takluyver** [comment]
> Well I dropped my mac and got back to my ubuntu lenovo...

Welcome back to the dark side ;-). Or whichever side we are.
