### ISSUE TITLE
Increment number of steering council members in description

### ISSUE THREAD

**Issue by willingc** [jupyter/jupyter.github.io#95]
After adding Sylvain to the steering council, there are now 11 steering council members displayed on the site but the text says there are 10. http://jupyter.org/about.html

**Comment by go-bears** [comment]
is this issue still open? I can fix it if you'd like. Thanks!

**Comment by rgbkrk** [comment]
Still open. Feel free!

**Comment by go-bears** [comment]
Thanks @rgbkrk!

**Comment by go-bears** [comment]
Think this issue can be closed? this merge fixes it: https://github.com/jupyter/jupyter.github.io/pull/125

**Comment by go-bears** [comment]
Actually I think _this_ merge fixed the steering council issue: https://github.com/jupyter/jupyter.github.io/pull/134/commits/06f2f9a8272fd7b311420a8fc809916b9b23c3c2

**Comment by rgbkrk** [comment]
Ah, yeah. Thanks again @go-bears.
