### ISSUE TITLE
Deployment/usage interactive map

### ISSUE THREAD

**Issue by fperez** [jupyter/jupyter.github.io#96]
We should try to collect data for (we already have some in our [education listing](https://docs.google.com/spreadsheets/d/12yRKOBuGXl1-g1qQpG1DUe12FNiNr0jpvBK1jyc2xFU/edit#gid=320200753)) , and display on the website, an interactive map that shows, as a starter:
- Uses of Jupyter in education.
- Deployments of JupyterHub.

For each of these, I'm imagining a map marker (probably different colors), which upon hover/click, pops up a small info note with a short description and a link, if relevant, to e.g. the course website or relevant github repo.

If a given deployment uses both Hub and is for education, we can use a different marker.

We were discussing today with @SylvainCorlay whether using the ipyleaflet widget might be a good solution for this...

**Comment by SylvainCorlay** [comment]
It seems like a perfect usecase for the static widgets.

**Comment by ellisonbg** [comment]
Love the idea of using the leaftlet widget - we could provide a link to the
notebook that generated it.

On Tue, May 31, 2016 at 4:29 PM, Sylvain Corlay <notifications@github.com>
wrote:

> It seems like a perfect usecase for the static widgets.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jupyter/jupyter.github.io/issues/96#issuecomment-222851458>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABr0CGy7q8IeJGpTm5-MPAEwRmKVWGWks5qHMRMgaJpZM4IrBKf>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cameronoelsen** [comment]
We are currently thinking of making a page for each of the Jupyter subproducts (including JupyterHub). I think the JupyterHub page would be a perfect place to showcase this!

**Comment by palewire** [comment]
Since this ticket has been inactive for four years, I'm going to close as stale. If you'd like to continue the discussion, feel free to chime in.
