### ISSUE TITLE
small remark: jupyter.org raises a "gives no information about its identity" warning on firefox

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyter.github.io#97]
![jupyter_org](https://cloud.githubusercontent.com/assets/4312421/15798411/87ce1dec-2a38-11e6-9af1-451fe92c8191.png)

**Comment by minrk** [comment]
Jupyter.org is behind cloudflare's ssl. I wonder if there's something different we should be doing. @rgbkrk?

**Comment by rgbkrk** [comment]
Since we're on the free plan, I'm not sure how much else we can change there. We could run our own but then we have more infra. to manage for what's a static page served underneath by GitHub pages.

**Comment by minrk** [comment]
Having looked into it a bit, I think the warning is actually about images coming from http rather than https, because the warning only shows up on a couple of pages. I think we can fix this.

**Comment by rgbkrk** [comment]
Ok, awesome.
